### ISSUE TITLE
plans to clone this for nodenv?

### ISSUE THREAD

**Issue by jasonkarns** [ianheggie/rbenv-env#1]
I'd expect to see:
- PATH
- NODE_*
- NODENV_*
- NPM_*

**Comment by ianheggie** [comment]
Check add_node_envs branch to see if it solves the problem (I can't test as I no longer use rbenv and don't use node), if not send me a pull request with working test and I will include it. Note - rbenv-env already displays PATH, it just doesn’t display PATH*

**Comment by jasonkarns** [comment]
thanks, i forgot this was still open. I'll probably fork this under the @nodenv org as nodenv-env

**Comment by jasonkarns** [comment]
@ianheggie i noticed that you merged node env var checking into rbenv-env. Was that intentional? As a user, I'm not sure that I'd expect (or want) `rbenv env` to emit node-specific env vars. I've been procrastinating on forking this and putting a nodenv-env plugin under the nodenv org. If I do that, would you want to revert the node behavior from here?

**Comment by ianheggie** [comment]
@jasonkarns - I would remove the node env checking if you forked this into a node specific plugin.
