### ISSUE TITLE
Volunteer to take over maintenance

### ISSUE THREAD

**Issue by jasonkarns** [ianheggie/rbenv-env#5]
I'm the primary active maintainer of the nodenv suite (core and plugins). I also maintain a fork of this plugin in particular, as a nodenv plugin.

I'd be interested in taking over maintenance. In particular, I would like to merge the two plugins such that the same plugin provides both nodenv and rbenv bins.

Interested?

**Comment by whteBaerd** [comment]
I need ebrew to anderstend well but yes if you frind of github and you came onli to help me. YeS  i intersting. But i need to sleep naw i am very taierd.thanks

**Comment by ianheggie** [comment]
> I'm the primary active maintainer of the nodenv suite (core and plugins). I also maintain a fork of this plugin in particular, as a nodenv plugin.
> 
> I'd be interested in taking over maintenance. In particular, I would like to merge the two plugins such that the same plugin provides both nodenv and rbenv bins.
> 
> Interested?

yes, I have moved this to a collaboration org and team and sent the invites for you to the three rbenv* repos

**Comment by jasonkarns** [comment]
@ianheggie apologies, I missed the invite before it expired. care to send again? (or anyone else in @Purple-Devs who already accepted and has the necessary permissions)
